# Basic Site Settings
locale                   : "China"
title                    : "Wei Yu Ma"
title_separator          : "-"
name                     : &name "Wei Yu Ma"
description              : &description "Master's student at UCAS, focusing on Game AI research"
url                      : https://histmeisah.github.io # 假设您的GitHub用户名是casia22
baseurl                  : "" 
repository               : "histmeisah/histmeisah.github.io"

# Site Author
author:
  # Biographic information
  avatar           : "profile.png"
  name             : "Wei Yu Ma"
  bio              : "Master's student at UCAS | Game AI Researcher | Former StarCraft II Pro-gamer"
  location         : "Beijing, China"
  employer         : "University of Chinese Academy of Sciences"
  uri              : "http://marl.ia.ac.cn/people/maweiyu.html"
  email            : "sc2meisah@gmail.com; maweiyu2022@ia.ac.cn"

  # Academic websites
  arxiv            : # https://arxiv.org/search/?searchtype=author&query=Wei+Yu+Ma
  googlescholar    : "https://scholar.google.com/citations?user=_waWSjEAAAAJ&hl=zh-CN"
  orcid            : # 如果您有ORCID ID可以添加
  
  # Repositories and software development
  github           : "histmeisah"
  
  # Social media
  twitter          : # 如果您有Twitter账号
  linkedin         : # 如果您有LinkedIn账号

# Publication Category
publication_category:
  conferences:
    title: 'Conference Papers'
  preprints:
    title: 'Preprints'
